### PR TITLE
Move agenthub within openhands

### PR DESCRIPTION
**Pull request by enyst**
- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

**End-user friendly description of the problem this fixes or functionality that this introduces**

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

This PR proposes to move `agenthub` within `openhands`. The `openhands-resolver` needs it, and I'm not sure why we would need to keep and manage them as separate modules...

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Comment by neubig** [comment]
CC @xingyaoww and @rbren 

I think this is a good change but it's a big one that might break some stuff so it's worth discussing.

Also @mamoodi , first release following this change would probably be a bump in the middle number (e.g. 0.10.0)

**Comment by enyst** [comment]
Manual tests with:
- `make run` and playing with a couple non-default agents, including one micro, and main agent
- build locally the pypi package (didn't try remote)
- (start to) run an eval to see that the agent version get read correctly (it made the right directory).

**Review by xingyaoww — COMMENTED** [review]
I think this is a good idea!

The only concern I'm having is that: currently runtime track changes in implementation by tracking the tarball from source distribution
https://github.com/All-Hands-AI/OpenHands/blob/909e332207ae25e2db23b12f65d21c8f5cf7a745/openhands/runtime/utils/runtime_build.py#L22-L73

Would moving `agenthub` into `openhands` further trigger runtime rebuild whenever agent code changes or no? 🤔 Maybe we can create a special sdist only for runtime-client (e.g., only include all the imports in the `runtime/client/client.py`.

**Comment by li-boxuan** [comment]
@xingyaoww I don't think runtime rebuild is an issue because customers shouldn't run from source code anyways. They shall either use pre-built docker image or use OpenHands as a python library.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by neubig** [comment]
I'm OK with this change and would prefer we merge it soon if we merge it, but I'd like to defer to @xingyaoww about whether this is ready or not, given the concerns about hashing.

**Review by xingyaoww — APPROVED** [review]
LGTM! The runtime hash shouldn't be a huge issue - we can leave that for future optimization

**Pull request merged**
