### PR TITLE
add --silent to oh instructions for frontend tests to minimize token usage

### PR DESCRIPTION
**Pull request by tobitege**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

Tweak the openhands instructions so that the LLM should pass an extra `--silent`  parameter to reduce the verbosity of frontend tests,
which could otherwise result in thousands of log lines for the OpenHands repo frontend.

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Comment by amanape** [comment]
I can't seem to see a difference when passing the `--silent` flag (though I feel like it's something with my machine). I tried `npx vitest --silent` and `npm run test -- --silent` and can't spot a difference without the flag.

Does it ignore passing tests and only output failing ones?

**Comment by tobitege** [comment]
I'm trying to find the right params for this per Sonnet and it is mixed results thus far. Vitest just does a LOT of output including terminal updates (cursor movement, overwrite text), but that is all logged to the output and assumingly all passed to the LLM, which is not ideal.
Open to suggestions for other approaches.

**Comment by tobitege** [comment]
@amanape so I gave Sonnet a bit of the log from the FE tests (total is over 8000 lines!!!) and here's what she said:

-----

Ah, I see the issue. Those logs are coming from MSW (Mock Service Worker) which is used for mocking API requests in tests. The `--silent` flag isn't affecting these logs because they're being generated by MSW's setup.

To reduce this noise, you have a few options:

1. Add a custom reporter that filters out MSW logs:
```typescript:frontend/vitest.config.ts
// ... existing imports ...
export default defineConfig({
  test: {
    // ... other config ...
    reporters: ['basic'],
    silent: true,
    setupFiles: ['./test/setup.ts'], // Make sure MSW setup has lower log level
  }
})
```

2. Or modify your MSW setup file to disable logging:
```typescript:frontend/test/setup.ts
import { setupServer } from 'msw/node'
import { beforeAll, afterAll, afterEach } from 'vitest'

// Configure MSW to be quiet
const server = setupServer()

beforeAll(() => {
  // Disable MSW logging
  server.listen({ onUnhandledRequest: 'bypass' })
})

afterAll(() => server.close())
afterEach(() => server.resetHandlers())
```

The `onUnhandledRequest: 'bypass'` option should reduce a lot of the MSW logging noise. Let me know if you need help locating where MSW is set up in your project to make these changes.

-----

Is this something worthwhile looking into further?

**Comment by amanape** [comment]
Can you share the head of the 8000 line long test output? MSW shouldn't log anything for most of them so I wonder what is causing so many.

Sonnet is right about bypassing them though. We can do it here:
https://github.com/All-Hands-AI/OpenHands/blob/037d770f66ca86fde697ec72a538af09796f70a9/frontend/vitest.setup.ts#L15-L22

Still unsure what `--silent` does and the official documentation doesn't explain much. If it silences all tests then we probably shouldn't enable it (since the agent can get good data from seeing the tests). On the other hand, if it only outputs failing tests, then it is a perfect alternative to outputting all of them

**Comment by tobitege** [comment]
example log with the parameters Sonnet suggested:
```
npm run test -- --silent --reporter=basic

> openhands-frontend@0.13.0 test
> vitest run --silent --reporter=basic


 RUN  v1.6.0 /mnt/d/github/OpenDevin/frontend

11:54:13:758 [websocket] constructing the interceptor...
11:54:13:761 [websocket] constructing the interceptor...
11:54:13:761 [websocket] constructing the interceptor...
11:54:13:758 [websocket] constructing the interceptor...
11:54:13:769 [websocket] constructing the interceptor...
11:54:13:795 [websocket] constructing the interceptor...
11:54:13:949 [websocket] constructing the interceptor...
11:54:13:991 [client-request-interceptor] constructing the interceptor...
11:54:13:991 [client-request-interceptor] constructing the interceptor...
11:54:13:991 [client-request-interceptor] constructing the interceptor...
11:54:13:991 [client-request-interceptor] constructing the interceptor...
11:54:13:992 [client-request-interceptor] constructing the interceptor...
11:54:13:991 [xhr] constructing the interceptor...
11:54:13:991 [fetch] constructing the interceptor...
11:54:13:991 [setup-server] constructing the interceptor...
11:54:13:991 [client-request-interceptor:on] adding "request" event listener: async ({ request, requestId, controller }) => {
        const response = await handleRequest(
          request,
          requestId,
          this.handlersController.currentHandlers().filter((handler) => {
            return handler instanceof HttpHandler || handler instanceof GraphQLHandler;
          }),
          this.resolvedOptions,
          this.emitter
        );
        if (response) {
          controller.respondWith(response);
        }
        return;
      }
11:54:13:991 [xhr:on] adding "request" event listener: async ({ request, requestId, controller }) => {
        const response = await handleRequest(
          request,
          requestId,
          this.handlersController.currentHandlers().filter((handler) => {
            return handler instanceof HttpHandler || handler instanceof GraphQLHandler;
          }),
          this.resolvedOptions,
          this.emitter
        );
```

I'll give your code snippet a try how the output is next.

**Comment by tobitege** [comment]
I tried several suggestions by Sonnit to make changes to the vitest.setup.ts file and also node.ts etc. regarding the MSW.
But this isn't doing anything in my WSL, the log output remains immense. 😞

**Comment by tobitege** [comment]
I originally was thinking of the issue when I saw this action log:
https://github.com/All-Hands-AI/OpenHands/actions/runs/11731090268/job/32680393593
So I'm wondering if the vitest-related params would reduce that kind of output (and we can ignore for now the logs I see in my WSL)?

**Comment by amanape** [comment]
Yeah let's try. The issue is that the console logs the states of when it starts, loads, and completes, polluting the terminal and makes it look long. It doesn't help that due to the implementation of some tests, the "loading" indicator is rendered a few times until the test completes.

We can also add the `--hideSkippedTests` and `--reporter=dot` flags

**Comment by amanape** [comment]
We can also consider [creating a custom reporter](https://vitest.dev/advanced/reporters.html) that only returns failed tests

**Pull request closed without merging**
