### PR TITLE
Remove file editing functionality from UI

### PR DESCRIPTION
**Pull request by rbren**
This PR removes all file editing functionality from the UI, making it read-only. Changes include:

- Removed code editor component and its actions
- Removed file upload and editing capabilities from file explorer
- Removed editing capabilities from files context
- Removed file editing hooks
- Removed supporting components
- Created a new simplified file viewer component

Users can still use VS Code to edit files if needed, but the OpenHands UI itself is now read-only.

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:c9b9bac-nikolaik   --name openhands-app-c9b9bac   docker.all-hands.dev/all-hands-ai/openhands:c9b9bac
```

### CODE REVIEW

**Comment by mamoodi** [comment]
Please ping me when this is ready to test. Seems like it's removing more than needed (file upload?)

**Comment by rbren** [comment]
I intentionally removed file upload because VS Code supports it, and it's really finicky. Happy to revert that piece if people find it useful though

**Comment by rbren** [comment]
Seems to be working well!

**Comment by enyst** [comment]
Just to make sure: if we implement LSP, we still want this gone? Because we [might](https://github.com/All-Hands-AI/OpenHands/issues/1934) implement LSP.

Personally I don't miss it on the web at all. 🤷 (Though I miss much, much deeper vscode integration.)

**Comment by rbren** [comment]
Yeah I think LSP still buys us a lot for agent editing!

**Review by tofarr — APPROVED** [review]
🍰

**Pull request merged**
