### PR TITLE
Fix issue #4830: [Bug]: Copy-paste into the "What do you want to build?" bar doesn't work

### LINKED ISSUE #4830: [Bug]: Copy-paste into the "What do you want to build?" bar doesn't work
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Currently, copy-pasting into the "What do you want to build?" bar in the chat screen does not result in any content being pasted. I tried both Cmd-V and using "Edit -> Copy".

It'd be good if we could write a frontend test to reproduce the bug and then fix it.

### OpenHands Installation

app.all-hands.dev

### OpenHands Version

_No response_

### Operating System

MacOS

### Logs, Errors, Screenshots, and Additional Context

Screenshot 2024-11-07 at 12 51 07 PM

### PR DESCRIPTION
**Pull request by openhands-agent**
This pull request fixes #4830.

The issue has been successfully resolved. The AI identified and fixed the core problem where text pasting wasn't working in the chat input bar. The solution involved:

Automatic fix generated by [OpenHands](https://github.com/All-Hands-AI/OpenHands/) 🙌

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:868c3c0-nikolaik   --name openhands-app-868c3c0   docker.all-hands.dev/all-hands-ai/openhands:868c3c0
```

### CODE REVIEW

**Review by neubig — COMMENTED** [review]
Looks like a perfect fix to me, amazing. But @amanape could you double-check?

BTW: I ran locally before and after and confirmed that this did indeed fix the bug.

**Comment by amanape** [comment]
Oh I see. @xingyaoww's chat input PR did this but I changed the position of the `event.preventDefault()` incorrectly. Looks like it caused it to fail and OpenHands fixed it again!

The only thing that OpenHands missed by a tiny bit are the tests (though I'm more than glad of the fact that it has attempted to do so). We have a test files for the chat input:

https://github.com/All-Hands-AI/OpenHands/blob/main/frontend/__tests__/components/chat/chat-input.test.tsx

Instead, OpenHands created a new file.

Some events it utilizes could be improved if it read the previous tests (such as using `userEvent` over `fireEvent`).

BTW, is OpenHands instructed to write tests?

**Comment by openhands-agent** [comment]
New OpenHands update

**Comment by amanape** [comment]
Revert these commits. I noticed that it started over in the trajectory, I didn't seem to find my feedback there. It worked off the original issue it seems

**Review by neubig — CHANGES_REQUESTED** [review]
1. The tests should be added to the already-existing file: https://github.com/All-Hands-AI/OpenHands/blob/main/frontend/__tests__/components/chat/chat-input.test.tsx
2. Some lint rules are failing in frontend/src/components/chat-input.tsx

**Comment by openhands-agent** [comment]
New OpenHands update

**Review by neubig — APPROVED** [review]
LGTM, and I think that it reflects @amanape's comments as well.

**Review by neubig — CHANGES_REQUESTED** [review]
Tests are failing, we may need to use fireEvent instead of userEvent for just the case of copy-pasting images.

**Comment by openhands-agent** [comment]
New OpenHands update

**Review by neubig — APPROVED** [review]
I think this looks good now. I wasn't able to get tests working properly with userEvent, but if it's important to do so maybe we can do so in a follow-up PR.

**Pull request merged**
