### PR TITLE
Link the resolver link to its new migrated location

### PR DESCRIPTION
**Pull request by ryx2**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

The Readme.md link to where the github actions openhands-resolver is now pointing to the wrong location, as that codebase has migrated to within this repo

---
**Link of any specific issues this addresses**

Openhands-resolver was migrated in https://github.com/All-Hands-AI/OpenHands/pull/4964

### CODE REVIEW

**Review by neubig — APPROVED** [review]
Thanks a lot!

**Comment by mamoodi** [comment]
Wow @ryx2 we literally opened a PR that fixes this at the same time :O 
https://github.com/All-Hands-AI/OpenHands/pull/5060

**Comment by ryx2** [comment]
@mamoodi great minds think alike

**Comment by mamoodi** [comment]
Going to close this because it was updated already. Thank you ryx2!

**Pull request closed without merging**
