### PR TITLE
Add Anthropic Models to Cache Prompt

### PR DESCRIPTION
**Pull request by ColeMurray**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**
Adds support for Anthropic models with 'anthropic/' prefix in cache prompting.

---

**Give a summary of what the PR does, explaining any non-trivial design decisions**
This pull request addresses an issue where Anthropic models with the 'anthropic/' prefix were not being correctly identified for cache prompting support. The changes include:

1. Added two new entries to the `cache_prompting_supported_models` list:
   - 'anthropic/claude-3-5-sonnet-20240620'
   - 'anthropic/claude-3-haiku-20240307'

2. Retained the existing entries without the 'anthropic/' prefix to maintain backwards compatibility:
   - 'claude-3-5-sonnet-20240620'
   - 'claude-3-haiku-20240307'

This change ensures that the cache prompting feature correctly supports Anthropic models regardless of whether they are referenced with or without the 'anthropic/' prefix. This dual-entry approach allows for flexibility in model naming conventions while maintaining support for existing configurations.

The decision to keep both prefixed and non-prefixed versions was made to:
1. Support users who may be using the models with the 'anthropic/' prefix in their configurations.
2. Maintain compatibility for users who are already using the non-prefixed versions.

---

**Link of any specific issues this addresses**
Fixes https://github.com/All-Hands-AI/OpenHands/issues/3774: Incorrect identification of Anthropic models in prompt cache supported models

### CODE REVIEW

**Review by enyst — APPROVED** [review]
Thanks for the fix!

This list we have will be a pain to keep updated... 😅 I hope liteLLM will support this feature in a more generic way in the future. For now it's good to have it working.

**Comment by tobitege** [comment]
This shouldn't be necessary, iirc the model name is compared to be in the array entry name, so we don't need to add prefixed versions.

**Review by tobitege — CHANGES_REQUESTED** [review]
Please see my comment in the convo.

**Comment by enyst** [comment]
> This shouldn't be necessary, i.e. the model name should be compared to be in the array entries' name (not equality), so we don't need to add prefixed versions.

I thought about that, but how about Anthropic models hosted elsewhere, like Bedrock?

**Review by tobitege — APPROVED** [review]
LGTM
Thank you for your contribution! 👍

**Pull request merged**
