### PR TITLE
refactor(frontend) Refactor and move components

### PR DESCRIPTION
**Pull request by amanape**
The objective of this PR is to
- break down large components (approximately > 150 lines) into smaller ones,
- move components into appropriate directories

Components are organized into folders based on their **domain**, **feature**, or **shared functionality**.

```sh
components
├── features # Domain-specific components
├── layout
└── shared # Shared UI components
```

- Added custom `base-button` to TailwindCSS for common button styles

This PR does not break down or merge some of the modal components as much as I initially planned. I hope to address this soon by implementing the Compound Component Pattern, which should provide a more convenient and flexible way to build them.

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:e31a1fd-nikolaik   --name openhands-app-e31a1fd   docker.all-hands.dev/all-hands-ai/openhands:e31a1fd
```

### CODE REVIEW

**Review by rbren — COMMENTED** [review]
There's a LOT here--is there an easy way to break it down into smaller PRs?

I assume this is all just refactoring and no functional changes--if you're confident w/ it I'm happy to approve but it's a lot to review 😅

**Comment by amanape** [comment]
Yes it is a lot, I recommend you switch to the branch on your local IDE so the changes will become clear. 

What I've done:
1. Break down components into smaller ones (e.g., `jupyter.tsx` into `jupyter.tsx`, `jupyter-cell.tsx`, etc...)
2. Organize them into folders (`features/jupyter/jupyter.tsx`, `features/jupyter/jupyter-cell.tsx`, etc...)
3. Update imports

There is no change in behaviour or logic, only reducing component size/complexity, removing duplicates (e.g., two different `loading-spinner.tsx`, moving some logic into functions and into utils (e.g., `parse-cell-content.ts`)

**Comment by amanape** [comment]
Sorry, I know it is a lot but the alternative would have been ~10-20 different PRs for breaking down and/or moving each component. Since there is no behaviour/logic changes, I thought I'd just submit it at once. It is more of a "look at the IDE file tree PR" rather than testing features

**Review by rbren — APPROVED** [review]
sounds like this is mostly just copy/paste, so the diff isn't as scary as it looks. 🍰

**Pull request merged**
