### PR TITLE
fix(browser): reduce the info we put into a webpage

### PR DESCRIPTION
**Pull request by xingyaoww**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

This PR reduce the info we put into a webpage - otherwise it can get too large and clustter the UI.

---
**Link of any specific issues this addresses**

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:bae4992-nikolaik   --name openhands-app-bae4992   docker.all-hands.dev/all-hands-ai/openhands:bae4992
```

### CODE REVIEW

**Comment by mamoodi** [comment]
@xingyaoww this doesn't seem to fix it.

**Comment by xingyaoww** [comment]
@mamoodi i guess if that's the case, we either have to have the ability to optionally disable browsing & wait for the screenshot-based browsing then :(

**Comment by xingyaoww** [comment]
@x66ccff I believe @adityasoni9998 is working on screenshot-based browsing in https://github.com/All-Hands-AI/OpenHands/pull/4773 - We need to get that in first before we can explore omniparser

**Comment by xingyaoww** [comment]
Let's close this one for now. This should be fundamentally solved when screenshot-based browsing is merged.

**Pull request closed without merging**
