### PR TITLE
(enh) Update Docker pull data in place

### PR DESCRIPTION
**Pull request by WannaTen**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**

Update Docker pull data in place, instead of outputting data for the same layer on different lines.

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

- output docker pull infos in-place

---
this is current docker pull output, same layer outputs on different lines:
docker2

after added in-place output:
image

### CODE REVIEW

**Comment by WannaTen** [comment]
@tobitege  Hi, Tobi, can you take a review at this code?  I remember you previously optimized the output here.

**Comment by tobitege** [comment]
> @tobitege Hi, Tobi, can you take a review at this code? I remember you previously optimized the output here.

Hey, thanks for this! Luv it, especially since it doesn't need an extra dependency! 👍 

I don't know if you wouldn't mind to add some small unit test for this, too? But not a requirement from me for this PR.

**Comment by tobitege** [comment]
@WannaTen - nevermind my comment about unit test above. :)

**Review by tobitege — APPROVED** [review]
Very nice enhancement, lgtm! Thank you!

**Pull request merged**
