### PR TITLE
docs: improve evaluation README with proper links and formatting

### PR DESCRIPTION
**Pull request by young010101**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Review by neubig — CHANGES_REQUESTED** [review]
Hey @young010101 , really sorry that I didn't see your PR before doing this, but I actually just queued up a big refactor of the eval directory here #5223 . I'll block this PR for now, but we can revisit it when #5223 is merged.

**Comment by young010101** [comment]
> Hey @young010101 , really sorry that I didn't see your PR before doing this, but I actually just queued up a big refactor of the eval directory here #5223 . I'll block this PR for now, but we can revisit it when #5223 is merged.

Thanks for your feedback! I'll wait for #5223 to be merged and then update my PR accordingly.

**Comment by mamoodi** [comment]
The refactor is finished in case you want to continue with this @young010101

**Comment by mamoodi** [comment]
Looks good! Thanks!

**Review by mamoodi — APPROVED** [review]

**Review by neubig — APPROVED** [review]

**Pull request merged**
