### PR TITLE
revert #3871 dockerfile template: don't write to .bashrc file

### LINKED ISSUE #4094: [Bug]: Weird Bash-related Runtime Bug
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

When execute command `python --version`, the bash wouldn't run the command for me, instead telling me: `
bash: --version: command not found`

image

But `echo "python --version" | eval` works:

image

And `which python` also works:

image

This is also reported by multiple people (cc @RajWorking & Sanidhya)

### Current OpenHands version

```bash
main, `9df395cc67f5a2487e6bdebd90f37cfd491a9eef`
```

### Installation and Configuration

```bash
Building a runtime image based on `python:3.11-bookworm`:

/runtime/test_eval_images.py
"""Tests for SWE-Bench evaluation images."""

import os

import pytest
from conftest import (
    TEST_IN_CI,
    _close_test_runtime,
    _get_sandbox_folder,
    _load_runtime,
)

from datasets import load_dataset

from openhands.core.config import LLMConfig, AppConfig, SandboxConfig
from openhands.core.logger import openhands_logger as logger
from openhands.events.action import CmdRunAction
from openhands.events.observation import CmdOutputObservation

def test_python_container(temp_dir, box_class):
    dummy_metadata = EvalMetadata(
        agent_class='CodeActAgent',
        llm_config=LLMConfig(),
        max_iterations=30,
        eval_output_dir='dummy',
        start_time='dummy',
        git_commit='dummy',
    )

    config = AppConfig(
        run_as_openhands=False,
        sandbox=SandboxConfig(
            base_container_image='python:3.11-bookworm',
            enable_auto_lint=True,
            use_host_network=False,
            # large enough timeout, since some testcases take very long to run
            timeout=300
        ),
        # do not mount workspace
        workspace_base=None,
        workspace_mount_path=None,
    )

    runtime = _load_runtime(temp_dir, box_class, config_override=config)

    obs = runtime.run_action(CmdRunAction(command='python --version'))
    assert isinstance(obs, CmdOutputObservation)
    logger.info(obs, extra={'msg_type': 'OBSERVATION'})
    import pdb; pdb.set_trace()



Then `DEBUG=true pytest -vvxss tests/runtime/test_eval_images.py::test_python_container`
```

### Model and Agent

_No response_

### Operating System

_No response_

### Reproduction Steps

_No response_

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by tobitege**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**

Revert #3871 dockerfile template (.bashrc runtime changes) (Fix #4094 )

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

Fixes bash issues due to empty env vars 😔 

Coincidentally, also applied a workaround for transient qemu docker errors in workflows

### CODE REVIEW

**Review by neubig — COMMENTED** [review]
Would it be possible to add a test to make sure this doesn't get broken again?

**Comment by tobitege** [comment]
> Would it be possible to add a test to make sure this doesn't get broken again?

This PR is a full revert of the dockerfile.j2 template to how it was before.

**Comment by xingyaoww** [comment]
Yeah, i think simply adding a test that runs `python --version` into `test_bash.py` should do the trick

**Comment by tobitege** [comment]
Oh, right. Adding one with next commit

**Comment by tobitege** [comment]
@xingyaoww - I can't add the test in this PR as the same issue will make it fail, have to do it after merge

**Review by xingyaoww — APPROVED** [review]

**Comment by tobitege** [comment]
upcoming test for this:
grafik

**Pull request merged**
