### PR TITLE
feat(frontend): Add feedback button

### PR DESCRIPTION
**Pull request by amanape**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
image

Redirects to a feedback form

---
**Link of any specific issues this addresses**

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:e158775-nikolaik   --name openhands-app-e158775   docker.all-hands.dev/all-hands-ai/openhands:e158775
```

### CODE REVIEW

**Review by tobitege — APPROVED** [review]
LGTM (haven't tried the live link, though)

**Comment by enyst** [comment]
I think the feedback form should have an "other" option.

I must have seen some experiments out there, although I don't know how good or open to users they were.

**Review by rbren — CHANGES_REQUESTED** [review]
Let's pause on this for a minute--I'm speaking with Paul later this week and will ask for his thoughts here.

The "chat" icon is probably a little ambiguous in our context, so I think we need a better one here

**Comment by mamoodi** [comment]
@rbren any update on the result of your meeting?

**Comment by mamoodi** [comment]
Going to close this for now. Please reopen when discussions are done and PR is ready again.

**Pull request closed without merging**
