### PR TITLE
Add resizable and collapsible panel layout

### PR DESCRIPTION
**Pull request by tofarr**
Resurrected the resizer component. (This was in place last August)
image

Fixes https://github.com/All-Hands-AI/OpenHands/issues/5894

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:505e8e0-nikolaik   --name openhands-app-505e8e0   docker.all-hands.dev/all-hands-ai/openhands:505e8e0
```

### CODE REVIEW

**Review by neubig — COMMENTED** [review]
Thanks for this, a few notes!

1. I accidentally did some duplicate work and opened this PR, sorry: https://github.com/All-Hands-AI/OpenHands/pull/5896
2. Overall the code looks nice and it worked in my environment. But It seems to have introduced a regression with respect to the design being reactive to small screen widths. Here's the current one in this PR:

Screenshot 2024-12-31 at 6 38 30 AM

and main for reference:

Screenshot 2024-12-31 at 6 38 46 AM

**Comment by tofarr** [comment]
@neubig Responsive design should now work again:
image

**Review by neubig — APPROVED** [review]
This looks great code-wise, and I confirmed that all the functionality works as expected. Thanks for this, it'll be excellent to have!

**Comment by rbren** [comment]
Not sure what happened here but you can see it in the last screenshot there--there's a style regression here. Going to revert for now

**Comment by rbren** [comment]
Screenshot 2024-12-31 at 9 21 19 AM

**Pull request merged**
