### PR TITLE
feat(runtime) Add runloop runtime implementation

### PR DESCRIPTION
**Pull request by ross-rl**
- [x] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

Add a Runloop provided runtime implementation for use in Openhands

**End-user friendly description of the problem this fixes or functionality that this introduces**

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
This PR adds a Runloop Devbox provided 'runtime' / sandbox environment for use in Openhands.  Implementation is complete to `runtime/test_bash` level.  Runloop api key is required for use - signup instructions can be found in README.md

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Comment by tobitege** [comment]
Hey @ross-rl 

thanks for the contribution. As far as I can tell, the status of this runtime is more in a Draft stage?
Since there are vital methods not implemented, how do you imagine the Runloop offers a benefit or helps? 🤔 
Maybe you could elaborate a bit on what the use case is and if I'm missing something here.

**Comment by ross-rl** [comment]
hey @tobitege! the use case is simply that Runloop would like to contribute to the ecosystem as a sandbox / runtime provider for Openhands.  In speaking with Robert and Xingyao, it's possible I was mistaken on what specifically was required to be Runtime compliant here.  I'm happy to implement the remaining methods and re-engage at that point

**Comment by tobitege** [comment]
> hey @tobitege! the use case is simply that Runloop would like to contribute to the ecosystem as a sandbox / runtime provider for Openhands. In speaking with Robert and Xingyao, it's possible I was mistaken on what specifically was required to be Runtime compliant here. I'm happy to implement the remaining methods and re-engage at that point

Hey,
yes, if the runtime has parity with implemented methods like the EventStreamRuntime, then the plugins and agents should work.
For now I've set this PR to draft for this.

**Comment by rbren** [comment]
@ross-rl I think the big thing left to do is implement ipython--lmk if you need any pointers there. We can leave browsing out for now.

When you pull in the latest changes, you might get a complaint about a new function related to zip files--we're going to remove that, so no need to implement

**Comment by ross-rl** [comment]
thanks for the feedback to both of you. @rbren will get to it

**Pull request closed without merging**
