### PR TITLE
Remove Cleanup stage in runtime tests

### PR DESCRIPTION
**Pull request by mamoodi**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**

Remove Cleanup stage in runtime tests to speed it up

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

Remove the cleanup stage to speed up run time tests

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Comment by mamoodi** [comment]
First Success: 15m52s total. Tests: 14m41s

**Comment by tobitege** [comment]
We gotta watch this veery closely to not run out of disk space without it.

**Comment by mamoodi** [comment]
> We gotta watch this veery closely to not run out of disk space without it.

Yeah that's why I'm doing multiple runs.

**Comment by tobitege** [comment]
Please wait for #3791 with merge of this as we'll have more concurrent containers open during runtime tests.

**Comment by tobitege** [comment]
I see that this action only takes like 2 minutes in the most recent runs. 
At that little time, I'd rather keep it in as the pros outweigh the cons.
Wdyt? @mamoodi @rbren

**Comment by mamoodi** [comment]
> I see that this action only takes like 2 minutes in the most recent runs. At that little time, I'd rather keep it in as the pros outweigh the cons. Wdyt? @mamoodi @rbren

If it's not needed, this shouldn't be here. It may be needed in the "Build Runtime" step but maybe not here. 2 minutes is still 2 minutes ;)

**Comment by tobitege** [comment]
> > I see that this action only takes like 2 minutes in the most recent runs. At that little time, I'd rather keep it in as the pros outweigh the cons. Wdyt? @mamoodi @rbren
> 
> If it's not needed, this shouldn't be here. It may be needed in the "Build Runtime" step but maybe not here. 2 minutes is still 2 minutes ;)

The Build Runtime is only doing one build at a time, but here we run 3 concurrent tests, each building its own container, that's why.

**Comment by mamoodi** [comment]
> > > I see that this action only takes like 2 minutes in the most recent runs. At that little time, I'd rather keep it in as the pros outweigh the cons. Wdyt? @mamoodi @rbren
> > 
> > 
> > If it's not needed, this shouldn't be here. It may be needed in the "Build Runtime" step but maybe not here. 2 minutes is still 2 minutes ;)
> 
> The Build Runtime is only doing one build at a time, but here we run 3 concurrent tests, each building its own container, that's why.

I'll wait for your PR to merge and then do some tests on here (Couple of runs, etc.). If tests are successful I suggest we merge. If in the future we run into this issue again, we can re-add it back with comments around it. How does that sound?

**Comment by tobitege** [comment]
Glad to see it ran fine this far!
I think we have to test this PR with a twin-PR coming from a forked repo, too, to test with these actions inside:
grafik

**Comment by rbren** [comment]
Agree we should merge this if the tests are passing consistently. We can always revert if the problem comes back

**Review by tobitege — APPROVED** [review]
LGTM

**Pull request merged**
