### PR TITLE
Don't send gemini settings when the llm is not gemini

### PR DESCRIPTION
**Pull request by enyst**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**

Don't send Gemini safety settings when the LLM is not Gemini

---

Tested with llama, AI studio / gemini.

### CODE REVIEW

**Comment by tobitege** [comment]
Let's use this one :)

**Review by tobitege — APPROVED** [review]
LGTM!
~~Small nit: are lines 145/146 still needed?~~ I'm too tired!

**Comment by enyst** [comment]
> LGTM! Small nit: are lines 145/146 still needed?

I think so, because they make it so that it's set when it's Gemini, no?

**Comment by tobitege** [comment]
> > LGTM! Small nit: are lines 145/146 still needed?
> 
> I think so, because they make it so that it's set when it's Gemini, no?

It's getting late, I misread the condition, nvm 😴 😄

**Comment by enyst** [comment]
Let's merge, `main` is broken otherwise, and take it from there. Thanks for manning the barricades at this hour! ❤️

**Pull request merged**
