### PR TITLE
Fix issue #3325: '[Documentation]: config.toml options should be documented on the doc web site'

### LINKED ISSUE #3325: [Documentation]: config.toml options should be documented on the doc web site
**What problem or use case are you trying to solve?**

It seems that there is no documentation on all the options available to configure OpenDevin on the documentation web site: https://github.com/All-Hands-AI/OpenHands/tree/main/docs

**Describe the UX of the solution you'd like**

It would be ideal if we could get some documentation on the web site.

**Do you have thoughts on the technical implementation?**

This should be created as its own page, and also added to the appropriate place in sidebars.ts: https://github.com/All-Hands-AI/OpenHands/blob/main/docs/sidebars.ts

To figure out what configuration options are available, we can look at the following file:
https://github.com/All-Hands-AI/OpenHands/blob/1109637efbe72b524473f0a4a4b84bbc74db3764/openhands/core/schema/config.py#L4

### PR DESCRIPTION
**Pull request by neubig**
- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

**End-user friendly description of the problem this fixes or functionality that this introduces**
This is a creation of some documentation about configuration, started by OpenHands.

No need to review, I'll work more on this.

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

---
**Link of any specific issues this addresses**
Fixes #3325

### CODE REVIEW

**Comment by neubig** [comment]
Will wait for #4138 to finish this.

**Comment by tobitege** [comment]
> Will wait for #4138 to finish this.

I'm wondering, does the resolver "see" the comments as well when it starts?

**Comment by neubig** [comment]
Right now it can't do PRs at all. For issues I don't think it can see comments on the issues yet, but that shouldn't be too hard to change.

**Comment by mamoodi** [comment]
@neubig just a gentle ping to see if this is worth pursuing.

**Pull request closed without merging**
