### PR TITLE
Fix issue #5480: [Bug]: Cannot recover from "Agent stuck in loop"

### LINKED ISSUE #5480: [Bug]: Cannot recover from "Agent stuck in loop"
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Once we stuck in "agent stuck in loop", we cannot send subsequent messages to the agent anymore.

image

### OpenHands Installation

Docker command in README

### OpenHands Version

_No response_

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by openhands-agent**
This pull request fixes #5480.

The issue has been successfully resolved. The AI agent implemented a comprehensive solution that addresses the core problem of being unable to send messages after an agent gets stuck in a loop. The solution:

1. Replaces the hard error (RuntimeError) with a graceful error state transition
2. Implements a recovery mechanism that allows new messages to be processed
3. Properly resets all relevant state variables when recovering
4. Follows existing patterns in the codebase (similar to traffic control implementation)
5. Includes test coverage to verify the fix

The changes allow users to continue interacting with the agent even after it gets stuck in a loop, which directly addresses the reported issue. The implementation is clean and follows existing patterns in the codebase, making it a maintainable solution.

For a human reviewer, I would summarize:
"This PR implements a graceful recovery mechanism for agents stuck in loops. Instead of throwing an error that prevents further interaction, the agent now enters an error state and can recover when receiving new messages. The implementation follows existing patterns (similar to traffic control) and includes full test coverage. All tests are passing."

Automatic fix generated by [OpenHands](https://github.com/All-Hands-AI/OpenHands/) 🙌

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:b5da59e-nikolaik   --name openhands-app-b5da59e   docker.all-hands.dev/all-hands-ai/openhands:b5da59e
```

### CODE REVIEW

**Comment by openhands-agent** [comment]
The workflow to fix this issue encountered an error. Please check the [workflow logs](https://github.com/All-Hands-AI/OpenHands/actions/runs/12296848979) for more information.

**Comment by enyst** [comment]
@openhands-agent Lets do a few things:
- ignore the rest of these comments if you saw them
- revert the changes in the diff of this PR
- read the agent controller, and then read the actual implementation of the stuck cases in the StuckDetector

IMPORTANT: in the stuck detector, we normally avoid processing user messages (which are MessageAction with source = 'user'), because we want to know if the agent is stuck so we look only the agent. But the issue this PR needs to address is that when the agent is stuck, the user cannot do anything to get it to continue. The reason is that if it wants to continue, we check again its last actions, we ignore the user message, and the agent actions still lead to the result that it's stuck!

We can get it "unstuck" if the user says something:
- use a boolean like almost_stuck to keep track of the actually stuck state
- set it when it gets stuck, and reset it when a user message is coming (and return false = no more stuck)
- make sure to tell out loud the solution and how it works, in complete concise phrases.

**Comment by openhands-agent** [comment]
Here's a concise overview:

Status: ISSUES REMAINING

Changes Made:
- Attempted to use `almost_stuck` but implemented it as a counter (0,1,2) instead of the requested boolean flag

Outstanding Issues:
1. `almost_stuck` needs to be implemented as a boolean, not a counter
2. No evidence of reviewing agent controller and StuckDetector implementation as requested
3. Missing implementation of boolean reset logic when user messages arrive

Next Steps:
1. Review agent controller and StuckDetector implementation
2. Simplify to use boolean `almost_stuck` flag
3. Implement proper reset behavior for user messages

The core requirements have not been met and the solution needs significant revision to align with the original feedback.

**Comment by openhands-agent** [comment]
The workflow to fix this issue encountered an error. Please check the [workflow logs](https://github.com/All-Hands-AI/OpenHands/actions/runs/12330884354) for more information.

**Pull request closed without merging**
