### PR TITLE
remove Exception in the agent

### PR DESCRIPTION
**Pull request by enyst**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**

If the LLM call results in an error, handle the error and notify the frontend of it.

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

Remove Exception in the agent.

---
**Link of any specific issues this addresses**
Fix https://github.com/All-Hands-AI/OpenHands/issues/4055

### CODE REVIEW

**Comment by tobitege** [comment]
I don't understand why this PR just goes about removing exception handling without providing the desired solution at the same time.
This will just reintroduce additional user frustration and extra support time in the meantime.

**Comment by enyst** [comment]
@tobitege yes, and I changed my mind about it, as we have discussed before. This PR is strictly the revert of a previous commit.

Is the original issue still happening for you with this revert?

**Review by xingyaoww — APPROVED** [review]
(this is very timely!)

This has been causing so much trouble for me during eval that i think this might be actually be necessary... 

It is just that we should instead send this exception to the FE, instead of catching it here, make it caught up by `AgentFinishAction`, and make eval outputs hard to interpret 😓

**Comment by enyst** [comment]
Sorry, I should have posted about it earlier. I've hesitated on it, because I know Tobi hated it, but I just didn't get the time to dig into the original problem that the old commit was trying to address.

I do agree we should do this. Otherwise we keep needing workarounds after workarounds, because of it.

**Pull request merged**
