### PR TITLE
SocketIO init event ordering

### PR DESCRIPTION
**Pull request by diwu-sf**
Fix for https://github.com/All-Hands-AI/OpenHands/issues/5661

### CODE REVIEW

**Comment by rbren** [comment]
@diwu-sf I think this is actually fixed in main now!

**Comment by neubig** [comment]
@tofarr if you can confirm that this is fixed in main could you close the PR? (thanks for the contribution @diwu-sf !)

**Review by tofarr — APPROVED** [review]
🍰  - and 🤦 for the previous version.

**Comment by diwu-sf** [comment]
I was away on vacation, thanks for taking care of this bug.

**Pull request merged**
