### PR TITLE
Edit linting: use line mapping to rule out irrelevant errors

### PR DESCRIPTION
**Pull request by li-boxuan**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**

Please read #3412 for more detail. To simply put, previous work uses the diff of linting error messages from pre-edit-lint and post-edit-lint to rule out "irrelevant" linting errors. The biggest flaw is that error messages could be generic - leading to both false positives and false negatives. This PR uses a more robust approach: line numbers.

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

Before edit, we run linting once, and record the error messages from the linter. After edit, we run linting once again, and also record the error messages. We then compare the line numbers from both pre-edit-lint and post-edit-lint. We rule out errors that are irrelevant to the edit (i.e. we remove errors that exist in both pre-edit-lint and post-edit-lint). This is non-trivial because line numbers might change. Luckily, since we only allow edits at a single place at a time, it is not too hard to figure out line mapping.

---
**Link of any specific issues this addresses**

#3412

### CODE REVIEW

**Comment by tobitege** [comment]
Great job on this tricky enhancement!
It looks good to me but I'll defer to @xingyaoww for approval as I suppose this will be sent to swe-bench?

**Comment by tobitege** [comment]
Great work! Since the tests run fine, I'd say LGTM.
Will run several Aider bench tests on this branch here and see if any related issue comes up -or- these instances come up successful now (compared to earlier tries).

**Comment by xingyaoww** [comment]
sounds good! I've finally got some of the eval pipeline working properly! Will start an eval on this PR today

**Comment by tobitege** [comment]
Just fyi, I did 15 different Aider bench instances and don't see new issues from this PR. 👍

**Comment by xingyaoww** [comment]
Weird enough, this PR actually brings a lot of degradation.. The current `main` is about 79 resolved, but this PR gets ~60
image

**Comment by tobitege** [comment]
Why do you get those "mv: cannot stat" errors? 🤔

**Comment by xingyaoww** [comment]
@tobitege those are un-related eval scripts things 🤣

**Comment by tobitege** [comment]
@li-boxuan please buzz us again once this is ready

**Pull request closed without merging**
