### PR TITLE
Update bug_template.yml to show app.all-hands.dev

### PR DESCRIPTION
**Pull request by neubig**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

Now people are starting to use app.all-hands.dev as a way to use OpenHands, we should probably add it to the bug template!

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=ghcr.io/all-hands-ai/runtime:0903da3-nikolaik   --name openhands-app-0903da3   ghcr.io/all-hands-ai/runtime:0903da3
```

### CODE REVIEW

**Review by enyst — CHANGES_REQUESTED** [review]
I'm torn about this, and I'd appreciate if we can take some time to think this through.

I can see why this makes sense from the AH perspective, it makes things easier. I can also see a benefit in the probable collaboration with some in AH team who are new to the project. 

You may want to consider the other likely consequence though: the hosted version is not an open source project. Every potential contributor looking at the issues in this repo will not be able to even think to do anything about it. Instead, they'll see a small team with inside information taking care of things. That appears to create a dynamic where people see themselves as users/consumers, not as contributors.

There are not many scenarios I can think of, where that isn't disincentivizing enthusiasm and contributions.

On a different, related note, how are you planning to deal with issues related to user support or billing? Would they be also part of this category?

**Comment by neubig** [comment]
These make sense!

Just to clarify though, the online site will be running the open source software, so open source contributors will certainly be able to fix issues that appear when people run things there. And the two apps will largely be at feature parity, so it's not like the online site is extremely exclusive or anything. I don't know if that helps?

In terms of user support in billing, I assume that we will have something separate for that, but we're not that far yet.

As one idea, maybe we could put this later in the list instead of first?

**Comment by mamoodi** [comment]
Yeah it's a tough call. If you all made the decision to add this, I would add the new option last so it doesn't show up as the default for now.

**Comment by enyst** [comment]
Just a detail on this:

> Just to clarify though, the online site will be running the open source software, so open source contributors will certainly be able to fix issues that appear when people run things there.

Of course, I'm sure the first is mostly the case. I'm not equally sure that the latter follows.

Not very relevant perhaps, but slightly related: a couple of nights ago I had to get out of bed to go try to repro an issue I was seeing on the site. Because amanape asked me to report it, and I realized I didn't know how to report it, I hadn't seen it before so I wasn't sure _whether it is on the project or only on the site_. I couldn't quite repro locally so I posted it for the site.(So I settled for the idea that there might be something site-specific, which may well not be accurate.)

An issue you cannot repro locally usually means a number of things. If it was seen on the site, however, it can mean a number of other things, specially when related to sessions, to auth, to user setup, to workspace setup, to permissions. 🤷

Surely, the agent is the same agent, but the agent errors might or might not be, I don't know, it depends. And people don't usually report _good_ behavior. 😅


Thank you for taking the time for this discussion. I only found out about this intention a couple days ago, and I honestly didn't get to grapple with the consequences. I do think it's non-trivial.

**Comment by neubig** [comment]
Thanks @enyst , I see where you're coming from, and I also understand as well. Debugging on the hosted version is more opaque for me as well because I'm not really able to dig through the logs.

Just as a thought experiment, what are the options that we have here:

1. Status quo: We keep the form the same. If so, every time I choose "installation method" I need to pick "docker" or "dev workflow", but neither of these apply when I'm using it on the site.
2. Current proposed solution
3. Some other solution such as having an entirely different workflow for reporting issues for site users? This seems a bit sub-optimal, because that would fragment knowledge about potential issues, and many or even most of the issues on the site stem from something in the oss repo.

I realize that there's no perfect solution here, but I still would lean towards "2." It seems easier logistically and a good way to keep things as open as possible and share knowledge with the whole community. But on the other hand, I do understand that you (and likely others) may be frustrated by seeing some bugs that are not stemming from the open source.

And yes, thanks from my side for the discussion too! As always, OpenHands is a community effort, and I want to make sure we end up with something that everyone is happy with!

**Comment by enyst** [comment]
Well said. Option 2 seems to make a lot of sense for simple, pragmatical reasons.

I may be dense, I admit I initially assumed that the hosted app support is, or will be, part of a separate project set up for "all-hands.dev" website (option 3).

Let me take your thought experiment and go deeper into option 2: same place. If the site is here, what does it bring with it and where are the limits? They are shifting.

1. You say that the issues will be mostly with `oh`, and I see why that is likely. But I hear on slack that AH has an NDA for people to sign. I have no idea what is that about. Where are users under NDA going to post about their issues?

Are we looking to see here posts like "there was also a lot of red error text but I don't know if I'm allowed to talk about it here because NDA"?

This is a pragmatical question as well as a values question. On the pragmatical side, I don't see how that would work in a public repo.

On the other side. "Open source but you're not allowed to speak" would seem to be the new normal. I do question whether that is a value this project should have and what consequences it will have on it.

**Comment by enyst** [comment]
The more I think about it, the more option 2 makes sense. But it implies, shall we say, a tighter integration between this project and the site. From the project side, that is.

So, speaking of the site, I noticed a funny thing or two. Unlike the above, they're not exactly pragmatical issues with option 2, but they are little interesting tidbits and worth bringing up IMO. 

2. The ToS for the website/service is public. Frankly most seems to be boring legalese, but there's a rather amusing detail.

> The following are examples of kinds of content and/or uses that are illegal or prohibited...[AH reserves the right to...] including reporting the violator to law enforcement authorities.

Then a bunch of bad things follow. Really bad. Law enforcement authorities bad. Then among them:

>engage in or use any data mining, robots, scraping, or similar data gathering or extraction methods.

About this...
IMG_0173


We are an AI open source project; we work with LLMs day in day out; and internet datasets; we have an agent grabbing axtrees and we may do in-context learning on up-to-date software library documentation, to name just a few. 😂

Data mining and web scraping public data are legal. And well, essential. (Private data is different, because it's private data, not because of data mining or scraping.)

Does AH want to prevent people from scraping its website? Well OK, it's its website, surely the AH team can monitor and try to stop it if so it wants, this paragraph is IMO unnecessary. Idk though, we may have forgotten to tell our agents. 😅

As a policy matter, I believe AH is mistaken to add this on its website.

(IMO, you're helping interests that would like nothing more than to make startups like this pay through their teeth for the crime of fine-tuning llama or browsing the internet archive. That's just my honest opinion.)

What is your position on this?

**Comment by enyst** [comment]
Last, and least.

3. The same ToS (it's disputable if anyone reads or cares about these things, and whether it'd be worth your time and resources to even think of enforcing, but well, words have meaning)

> **Competitors**: No employee, independent contractor, agent, or affiliate of any competing open source software development company is permitted to view, access, or use any portion of the Service without express written permission

A curious little detail... why single out "open source software development company", and not all competitors if so, is that a typo?

In the early days, "Devin" from "Cognition AI" apparently submitted a PR. I remember that when I brought it out in our slack, everyone was amused and excited. Is something like that becoming frown upon? Sorry, it was fun.

We also have a lot of issues posted in this repo, afaik roadmap-worthy, that describe or even include [screenshots from devin](https://github.com/All-Hands-AI/OpenHands/issues/1742). This... seems a little ironic.

On the other hand, please correct me if wrong, I think AH is not trying to enforce this. Then why say it? Legal stuff has the habit to become part of the shared understanding in a community. I believe people internalize it as shared values. Just like licenses. Just like it's meaningful that the license is MIT, a "live and let live" license.
image

**Comment by neubig** [comment]
Hi @enyst , thanks for sending! I just want to acknowledge that I saw this and will take a closer look but it might take a few days. CC @rbren for visibility too. Terms of service are obviously important but they need to reflect our values, so I'll take a close look at what we have now and circle back!

**Comment by neubig** [comment]
Thanks @rbren, 100% agree on revisiting the terms and thank you to @enyst for pointing this out (I didn't think as deeply about them as I should've either).

For the time being, I added "app.all-hands.dev" as one option but at the bottom of the list, and also added "Other" for other setups too. Let me re-request review, but I'm also happy to continue the discussion!

**Review by enyst — APPROVED** [review]
- That people will look for a way regardless is a good point
- I still don't understand the NDA issue, and it seems to me you will need another space anyway
- For the record, I only skimmed through the wall of legalese, there might be other things lurking in the dark. And yeah, it's not necessarily fun.

Let's go with this. I will not lie, I really appreciate the time taken to discuss this a bit, and in the same time I remain unconvinced on the concerns raised, I'm afraid. Sorry. But I don't think adding it to the template needs to take more time, _some_ template fix is becoming more useful since it's opening up access.

@rbren this PR already has cats, and cats always win, so I refrain from lawyer jokes. This time. No promise though, no way, no promise on that one!

**Comment by neubig** [comment]
Thanks a lot! And let's continue the discussion, these sorts of things are super important to discuss and get right, so in the future I'll try to run things by you whenever there are similar decisions to be made.

**Pull request merged**
