### PR TITLE
[Feat] Aider Benchmark

### LINKED ISSUE #3183: [Evaluation] Integrate Aider Editing Benchmark
**What problem or use case are you trying to solve?**

Integrate [Aider Editing Benchmark](https://github.com/paul-gauthier/aider/blob/main/benchmark/README.md). This will allow us to develop better editing approach without running the full SWE-bench.

**Describe the UX of the solution you'd like**

**Do you have thoughts on the technical implementation?**

Similar to other benchmarks in `evaluation/`.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by RajWorking**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**
Resolves  #3183

### CODE REVIEW

**Review by xingyaoww — COMMENTED** [review]
Thanks a ton for this! Do you mind adding a README.md to briefly explain what this benchmark does?

**Comment by tobitege** [comment]
readme should then also contain origin and license hint etc.

**Comment by xingyaoww** [comment]
I think we can add license stuff here: https://github.com/All-Hands-AI/OpenHands/blob/main/CREDITS.md

**Review by xingyaoww — COMMENTED** [review]
I just ran locally and confirmed this runs smoothly -- Great work @RajWorking! I think this is ready to merge after README.md is added.

**Comment by RajWorking** [comment]
Added README.md.

Also, upon running on the exercism python dataset with **gemini-1.5-flash**, the results were:
PASSED: **30**
TOTAL: **133**
SUCCESS RATE: **22.56%**

**Review by xingyaoww — APPROVED** [review]
LGTM! Thanks @RajWorking!

The Gemini scores look a bit low - I think there's a lot of room for improvements here - let's start working to improving the editing :D

@RajWorking If you are interested in exploring approaches to improve it LMK on slack DM! I can grant you some API credits if so

**Pull request merged**
