### PR TITLE
(enh) Improve CodeActAgent's file editing reliability

### PR DESCRIPTION
**Pull request by tobitege**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

A recurring issue for `CodeActAgent` and models like Sonnet is the plain removal of content and ignoring the fact, that `open_file` only shows a limited number of lines. The latter often results in Sonnet to just _assume_ that it did read the _full_ file, then edits with improper content and potentially corrupting the file (especially when > 100 lines).

Wording changes for
- `open_file`:  with regard to amount of displayed lines; written out method names for `scroll_up` / `scroll_down`
- `edit_file_by_replace`: mention this is for existing files and `to_replace` must be non-empty
- `system_prompt.j2` template: added several specific file-related operation hints

**TODO:**
- [X] Units tests are working
- [ ] Integration tests need regeneration

### CODE REVIEW

**Review by neubig — COMMENTED** [review]
This looks nice, but it'd be ideal to evaluate before we merge it in.

**Comment by tobitege** [comment]
> This looks nice, but it'd be ideal to evaluate before we merge it in.

Right, I'm still working on this one, thus still Draft.

**Comment by tobitege** [comment]
Doing more tests, trying to tweak more as some more issues persists., back to Draft for now.

**Comment by yufansong** [comment]
It is amazing that prompt change can have huge improvement on aider benchmark.

**Comment by tobitege** [comment]
Superseeded by #3610 , closing this now.

**Pull request closed without merging**
