### PR TITLE
chore(frontend): Update dependencies safely

### PR DESCRIPTION
**Pull request by amanape**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

---
**Link of any specific issues this addresses**

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:54443e0-nikolaik   --name openhands-app-54443e0   docker.all-hands.dev/all-hands-ai/openhands:54443e0
```

### CODE REVIEW

**Review by tofarr — APPROVED** [review]
🍰

**Comment by enyst** [comment]
We can update the dependabot yaml to group or exclude or whatever, if we have problems with some packages. For example, we separate there a few packages whose updates can mess things up or have in the past. Keeping them out of "all" group allows us to upgrade the rest more smoothly. If that helps here? Cc @amanape

**Comment by amanape** [comment]
Normally group updates shouldn't be an issue (though I prefer it if it were individual). It is just that this was left too long and it grouped some major changes (Vite v5 -> v6, React v18 -> v19) that I want to handle in a separate PR since they will require making additional changes in some of our components

**Review by enyst — APPROVED** [review]
Whatever you want. If this is temporary, we probably don't need to change the yaml.

**Pull request merged**
