### PR TITLE
Fix issue #5739: [Bug]: Move ./evaluation/swe_bench/scripts/cleanup_remote_runtime.sh to general eval utils

### LINKED ISSUE #5739: [Bug]: Move ./evaluation/swe_bench/scripts/cleanup_remote_runtime.sh to general eval utils
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

The functionality of `./evaluation/swe_bench/scripts/cleanup_remote_runtime.sh` is not limited to swe-bench, so instead it should be moved to the general evaluation utils folder.

### OpenHands Installation

Docker command in README

### OpenHands Version

_No response_

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

_No response_

### PR DESCRIPTION
**Pull request by openhands-agent**
This pull request fixes #5739.

The issue has been successfully resolved. The AI agent moved the `cleanup_remote_runtime.sh` script from its specific location in the swe-bench scripts directory (`/workspace/evaluation/benchmarks/swe_bench/scripts/`) to a more general and appropriate location in the evaluation utils folder (`/workspace/evaluation/utils/scripts/`).

PR Review Message:
This PR addresses the organization of utility scripts by moving `cleanup_remote_runtime.sh` from the swe-bench specific directory to the general evaluation utils folder. Since this script's functionality is not specific to swe-bench, this move makes the codebase more organized and the script more accessible for general use.

Changes made:
1. Created new directory: `/workspace/evaluation/utils/scripts/`
2. Moved `cleanup_remote_runtime.sh` from swe-bench specific location to the new general utils directory
3. No code changes were made to the script itself, only its location was changed

No tests were required as this was purely an organizational change with no functional modifications to the code.

Automatic fix generated by [OpenHands](https://github.com/All-Hands-AI/OpenHands/) 🙌

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:9691f85-nikolaik   --name openhands-app-9691f85   docker.all-hands.dev/all-hands-ai/openhands:9691f85
```

### CODE REVIEW

**Review by neubig — COMMENTED** [review]
LGTM

**Comment by enyst** [comment]
@openhands-agent Read the diff of this PR. You can see it moves a cleanup shell script from swe-bench to a general util directory. 

Look at evaluation sub-directories to understand the structure. Then find any reference in the swe-bench documentation, like its readme file, of the script that is moved. Update them to the new location.

Additionally. Search for duplicates of this script, that may exist in other benchmark subdirectories. Verify that any other cleanup script you find has the same contents with this script. If it's a duplicate indeed, remove it, and update references in .md files to the new location of the cleanup script.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the pr! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12449559613).

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the pr! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12449860142).

**Comment by enyst** [comment]
We're fixing the `openhands-agent` failure.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the pr! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12450219206).

**Comment by openhands-agent** [comment]
Based on the provided information, here is a concise overview:

Status: ✅ FULLY RESOLVED

Changes Made:
1. Cleanup script relocated to utils directory
2. Duplicate script removed from commit0_bench
3. Documentation updated in both affected directories

All original requirements have been met, with no remaining issues identified. The changes successfully consolidated the cleanup functionality while maintaining proper documentation references.

A human review is recommended to verify the specific implementation details.

**Review by enyst — APPROVED** [review]
Looking good!

**Pull request merged**
