### PR TITLE
style(frontend): Make modal backdrop darker

### PR DESCRIPTION
**Pull request by amanape**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
Backdrop opacity increased from 50% to 80%

**BEOFRE:**
image

**AFTER:**
image

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Comment by tobitege** [comment]
Only small feedback, it looks much better! Would there even be a "blur effect" available?

**Comment by amanape** [comment]
Sure, you mean a blur instead of how dark this is?

**Comment by tobitege** [comment]
> Sure, you mean a blur instead of how dark this is?

Hmm... both/either/or? Not sure 😄  I thought we had a while back a blurr effect, which was pretty good at "hiding" stuff?

**Comment by tobitege** [comment]
Fyi, I'm fine with either way, but since Robert brought this up, I'm only commenting.

**Comment by amanape** [comment]
Yes, we previously had an _animated_ blur effect from nextui's modals. We have our own modals now so we would need to give our backdrops a touch of blur too. Anything animated though I'd prefer doing at the very end unless its very simple and basic that could be done from a single line in Tailwind

**Comment by tobitege** [comment]
> Yes, we previously had an _animated_ blur effect from nextui's modals. We have our own modals now so we would need to give our backdrops a touch of blur too. Anything animated though I'd prefer doing at the very end unless its very simple and basic that could be done from a single line in Tailwind

Oh, I didn't remember that it was animated. Sounds like it'd be lots of extra effort with little gain then.

**Comment by amanape** [comment]
We can still make it blurred, just not a fade-in animation as it was

**Comment by amanape** [comment]
Maybe I should open a separate PR if we want it to be blurred or close this one. @neubig WDYT?

**Review by neubig — APPROVED** [review]
TBH: I think this PR looks fine for now. Maybe we can just go with it and iterate later if we want to change it.

**Pull request merged**
