### PR TITLE
[llm] Add app name for OpenRouter

### PR DESCRIPTION
**Pull request by xingyaoww**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**

OpenRouter has a way to tracking LLM usage from different App: https://openrouter.ai/

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

Following [this](https://docs.litellm.ai/docs/providers/openrouter), this PR adds the env var variable to make it easier for OpenRouter to track OpenHands' LLM usage.

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Comment by enyst** [comment]
Just a thought, I wonder if it's a bit cleaner if we add them in llm_config.py rather than llm.py. Specially since we seem to set them always, regardless if the user is using openrouter, they seem to belong in configurations. It's similar after all, with the cloud providers specific vars, of which we have a few.

**Comment by enyst** [comment]
I agree the overhead is not really an issue.

I just think they belong with other provider-specific stuff like `aws_region_name`, and those are defined in `llm_config.py`.

Even if we don't make them "actual" config values, just for code organization, I feel like they belong in that file.

**Comment by xingyaoww** [comment]
@enyst good point! Having `LLMConfig` as the centralized place for all the stuff is probably a good idea. Just moved it to `LLMConfig`

**Review by enyst — APPROVED** [review]
I'm thinking to move it completely out of llm.py 🤔 - but let's get this in, so you can focus on the fun edits stuff.

**Pull request merged**
