### PR TITLE
Revert "Feature: Add ability to reconnect websockets"

### PR DESCRIPTION
**Pull request by enyst**
Reverts All-Hands-AI/OpenHands#4526

Sorry, I'm trying to see it work locally and it doesn't work for me at all. I left a session disconnect, then:
- tried to send a message in the UI, I can see the message in the chat box, but nothing else happens
- I sent 'continue' => nothing happens
- then I clicked around on the UI, selected a file in the workspace => now it does send something to the server which fails, it seems disconnect closed the container and that cleaned it up, and it doesn't remake it. How is it supposed to work?

```
INFO:     127.0.0.1:51330 - "GET /api/list-files?path=opendevin%2F HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.47/containers/openhands-runtime-51af8ca7-9008-4ccd-80db-25aa254532fe/json
```

<details>
<summary>More logs</summary>
```
  File "/Users/enyst/repos/odie/openhands/runtime/impl/eventstream/eventstream_runtime.py", line 358, in _attach_to_container
    container = self.docker_client.containers.get(self.container_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/docker/models/containers.py", line 954, in get
    resp = self.client.api.inspect_container(container_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/docker/api/container.py", line 793, in inspect_container
    return self._result(
           ^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/docker/api/client.py", line 281, in _result
    self._raise_for_status(response)
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/.venv/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.47/containers/openhands-runtime-51af8ca7-9008-4ccd-80db-25aa254532fe/json: Not Found ("No such container: openhands-runtime-51af8ca7-9008-4ccd-80db-25aa254532fe")
```

</details>

In addition:
- session restore crash, that may not require a revert, it can be solved by this PR https://github.com/All-Hands-AI/OpenHands/pull/4796

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:bcfd4fc-nikolaik   --name openhands-app-bcfd4fc   docker.all-hands.dev/all-hands-ai/openhands:bcfd4fc
```

### CODE REVIEW

**Comment by tofarr** [comment]
Is this covered by https://github.com/All-Hands-AI/OpenHands/pull/4796 ?

**Review by xingyaoww — APPROVED** [review]
Let's temporarily revert this until we are sure things are fixed and comments in https://github.com/All-Hands-AI/OpenHands/pull/4526 is addressed 🙏

**Comment by xingyaoww** [comment]
As a side note, i think we should really create testcases on scenario @enyst brought up to prevent regression like this going forward

**Comment by enyst** [comment]
I agree. Sorry @tofarr , I'll be happy to take it back in when it's fixed!

**Pull request merged**
