### PR TITLE
Downgrade openhands-aci to 0.1.2

### PR DESCRIPTION
**Pull request by ryanhoangt**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

This PR is to:
- Downgrade openhands-aci to 0.1.2. It's bumped to 0.1.3 in https://github.com/All-Hands-AI/OpenHands/pull/5630, but there are some tag parsing logic that needs to be updated. The package will be upgraded in https://github.com/All-Hands-AI/OpenHands/pull/5508

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Comment by enyst** [comment]
Aaaah dependabot did it? 😅 

OK, if you see fit to undo. Is it problematic?

**Comment by ryanhoangt** [comment]
Yeah i have some changes in https://github.com/All-Hands-AI/openhands-aci/pull/21 to fix a bug Xingyao identified. The current regex parsing will not work and need to be updated

**Comment by enyst** [comment]
We could also exclude it from dependabot full group, make it its own group, so we can see it specifically.

**Review by enyst — APPROVED** [review]

**Comment by ryanhoangt** [comment]
Does using a fixed version work? i.e. will not be automatically updated by dependabot 🤔

**Comment by enyst** [comment]
> Does using a fixed version work? i.e. will not be automatically updated by dependabot 🤔 Previous I used ^ before the version number.

I never remember the answer to that, but I now think it's no. It won't work, as we have some others like ruff, and dependabot updates them.

Up to you - if you and Xingyao want, you can also decide to release only when you think it's suitable for integration in `openhands`. Otherwise, we add it to its own group in the yml and it's fine too. I'll go forward with this merge now, and we can for the next versions, whatever you want.

**Pull request merged**
