### PR TITLE
Replace browsergym with browsergym-core to reduce dependencies

### PR DESCRIPTION
**Pull request by neubig**
This PR replaces the dependency on `browsergym` with `browsergym-core` to reduce unneeded dependencies. The full `browsergym` package includes many additional dependencies that are not needed for our use case.

Changes:
- Changed dependency from `browsergym` to `browsergym-core` in pyproject.toml
- Updated poetry.lock to remove unneeded dependencies

All tests pass successfully, confirming that the core browsergym functionality works as expected.

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:355c208-nikolaik   --name openhands-app-355c208   docker.all-hands.dev/all-hands-ai/openhands:355c208
```

### CODE REVIEW

**Review by neubig — COMMENTED** [review]
Tests are now failing due to a missing dependency on "joblib". I expect that this was because joblib was included by browsergym, but it not explicitly included in our pyproject.toml file. We should also include a relevant version of joblib in pyproject.toml to adjust for this.

**Comment by openhands-agent** [comment]
New OpenHands update

**Comment by enyst** [comment]
@neubig Sorry, we can continue to fix it here, but just for discussion, have you seen this?
- https://github.com/All-Hands-AI/OpenHands/pull/5242

It's in the stage "thinking about" 😅 because:
- the envs can be part of the 'evaluation' poetry group, which is not normally run in CI
    - CI is or should be run with `poetry install --without evaluation,llama-index`
- but there's a browsing test with miniwob that will fail as long as they're not installed
- which I had some trouble disabling in a way that remains very visible (= not prone to be forgotten)
    - because, for example, Xingyao recently needed it, and used it, in the latest browser action PR
    - https://github.com/All-Hands-AI/OpenHands/pull/5285
    - I mean, totally removing or commenting it out seems the wrong thing to do
- this isn't a new problem, we have it already with llama-index, same thing, disabled in normal CI, should not be forgotten, needs a place to run and us keeping an eye on

So my current theory about how to fix this, is to move both the llama-index and evaluation groups tests to some other pipeline like we now have the integration tests one:
- https://github.com/All-Hands-AI/OpenHands/issues/5318#issuecomment-2509428447
- maybe even the same, or a new category like it?

**Comment by neubig** [comment]
Hey @enyst , I indeed had not seen that. Apologies! I'll look through carefully when I have a moment.

**Comment by neubig** [comment]
Closing in favor of #5242

**Pull request closed without merging**
