### PR TITLE
Clean up file logs

### PR DESCRIPTION
**Pull request by enyst**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

This PR proposes to clean up the file logs stripping the ANSI sequences.

Before:
```
    ^[[92m23:31:24 - openhands:DEBUG^[[0m: action_execution_server.py:167 - Action output:
    |**IPythonRunCellObservation**
    |[Code executed successfully with no output]
    |[Jupyter current working directory: /workspace]
    |[Jupyter Python interpreter: /openhands/poetry/openhands-ai-5O4_aCHf-py3.12/bin/python]
    |^[[92m23:31:24 - openhands:DEBUG^[[0m: event.py:89 - Event to dict: {'message': 'Code executed in IPython cell.', 'observation': 'run_ipython', 'content': '[Code executed successfully with no output]\n[Jupyter current working directory: /workspace]\n[Jupyter Python interpreter: /openhands/poetry/openhands-ai-5O4_aCHf-py3.12/bin/python]', 'extras': {'code': 'import os\nos.environ...
```

After:
```
    |19:28:20 - openhands:DEBUG: action_execution_server.py:167 - Action output:
    |**IPythonRunCellObservation**
    |[Code executed successfully with no output]
    |[Jupyter current working directory: /workspace]
    |[Jupyter Python interpreter: /openhands/poetry/openhands-ai-5O4_aCHf-py3.12/bin/python]
    |19:28:20 - openhands:DEBUG: event.py:89 - Event to dict: {'message': 'Code executed in IPython cell.', 'observation': 'run_ipython', 'content': '[Code executed successfully with no output]\n[Jupyter current working directory: /workspace]\n[Jupyter Python interpreter: /openhands/poetry/openhands-ai-5O4_aCHf-py3.12/bin/python]', 'extras': {'code': 'import os\nos.environ
```
---
**Link of any specific issues this addresses**

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:059046b-nikolaik   --name openhands-app-059046b   docker.all-hands.dev/all-hands-ai/openhands:059046b
```

### CODE REVIEW

**Review by xingyaoww — COMMENTED** [review]
I thought we intentionally use different color to print action/observation?

e.g. here
https://github.com/adityasoni9998/OpenHands/blob/6aba4621da5a1826df2966e130fdf1e74dbc08a4/openhands/core/logger.py#L37-L76

**Review by xingyaoww — APPROVED** [review]
ahh i see - you only change the **file** formatter - LGTM

**Comment by enyst** [comment]
Yes! Console is not affected.

**Review by tofarr — APPROVED** [review]
LGTM - Changing the format for files makes sense

**Pull request merged**
