### PR TITLE
feat: Always mount a Docker volume to use as workspace instead of host's disk

### PR DESCRIPTION
**Pull request by amanape**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**
This PR will attempt to accomplish:
- No mounting to host disk by default
- Instead, an option to use host disk should be available (in case existing users would prefer it)

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
Creates a volume (if one does not already exist) and mounts it instead of the host disk.

---
**TODO**
- [ ] Allow the user to set host disk as volume
- [ ] Clear/delete volume on new session

### CODE REVIEW

**Comment by tobitege** [comment]
I like the idea of a configurable volume to mount, _as an option_.

What is the reasoning to make this PR's approach the new, default behavior?

**Comment by rbren** [comment]
Stephan is working through a new default user flow that would avoid mounting by default (to avoid all the file permission and mounting issues we've seen). Instead, we'd nudge the user toward pushing/pulling from GitHub, or uploading/downloading files via the UI

**Comment by tobitege** [comment]
> Stephan is working through a new default user flow that would avoid mounting by default (to avoid all the file permission and mounting issues we've seen). Instead, we'd nudge the user toward pushing/pulling from GitHub, or uploading/downloading files via the UI

But the current mounting way will still be available then as an option, right?

**Comment by rbren** [comment]
Yup!

**Comment by amanape** [comment]
Oudated

**Pull request closed without merging**
