### PR TITLE
Fix issue #5527: Document repository customization and micro-agents

### LINKED ISSUE #5527: Customization of repos within the OpenHands app should be documented
**What problem or use case are you trying to solve?**

It is not obvious how to customize openhands to work well with new repos.

**Describe the UX of the solution you'd like**

The functionality for customization of prompts to specific repositories introduced in this PR should be documented in our documentation directory: https://github.com/All-Hands-AI/OpenHands/pull/4983

**Do you have thoughts on the technical implementation?**

I would suggest changing the current
```
* Prompting Best Practices
```

page to be hierarchical
```
* Prompting Best Practices
  * Characteristics of Good Prompts
  * Customizing Prompts for your Project
```

### PR DESCRIPTION
**Pull request by xingyaoww**
**End-user friendly description of the problem this fixes or functionality that this introduces**

This PR improves the documentation by:
* Adding clear instructions for customizing OpenHands for specific repositories
* Adding comprehensive documentation about micro-agents
* Updating sidebar structure for better organization

**Give a summary of what the PR does, explaining any non-trivial design decisions**

* Added a new section "Customizing Prompts for your Project" to the prompting-best-practices.md file
* Added a new micro-agents.md file documenting the micro-agent system
* Updated the sidebar structure to organize prompting-related documentation better

**Link of any specific issues this addresses**

Fixes #5527

### CODE REVIEW

**Comment by xingyaoww** [comment]
We should examine the logic added in https://github.com/All-Hands-AI/OpenHands/pull/4983 more carefully. OpenHands you should use GitHub API to read the diff to better understand it. 

Also, we lack documentation about micro-agents! You should understand markdown files under `openhands/agenthub/codeact_agent/micro` AND try to document it in a different markdown file.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the pr! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12283176173).

**Comment by openhands-agent** [comment]
Here's a concise overview of the changes and remaining issues:

Status: INCOMPLETE ❌

Unresolved Issues:
1. No evidence of examining PR #4983's logic via GitHub API
2. No analysis of micro-agents source code from `openhands/agenthub/codeact_agent/micro`
3. Cannot verify documentation quality due to lack of specific content details

Required Actions:
1. Properly examine PR #4983 and document findings
2. Analyze micro-agents source code before creating documentation
3. Provide specific details about documentation content and how it relates to the source code

Recommendation:
A new attempt should be made with focus on:
- Detailed analysis of PR #4983
- Thorough review of micro-agents source code
- Creation of documentation based on actual code understanding
- Clear documentation of findings and changes made

**Comment by openhands-agent** [comment]
The workflow to fix this issue encountered an error. Please check the [workflow logs](https://github.com/All-Hands-AI/OpenHands/actions/runs/12283176173) for more information.

**Comment by xingyaoww** [comment]
Now that above task is done. We should write more about HOW to contribute a micro-agent.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the pr! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12283820360).

**Comment by openhands-agent** [comment]
Overview of Changes and Remaining Issues:

Status: INCOMPLETE ❌

Resolved Items:
- None conclusively demonstrated

Remaining Issues:
1. No verification of PR #4983 diff examination
2. Missing concrete evidence of documentation structure implementation
3. No proof of micro-agent documentation additions
4. Lack of specific references to actual changes made

Key Problem: The response consists of plans and claims without substantiating evidence or concrete implementations. All major items remain unaddressed.

Recommendation: Need complete resubmission with:
- GitHub API diff analysis results
- Links to actual documentation changes
- Specific file references
- Evidence of implemented (not just planned) changes

**Comment by openhands-agent** [comment]
The workflow to fix this issue encountered an error. Please check the [workflow logs](https://github.com/All-Hands-AI/OpenHands/actions/runs/12283820360) for more information.

**Review by neubig — APPROVED** [review]
The documentation changes look good and address the issue well:

* Added clear instructions for customizing OpenHands for specific repositories
* Added comprehensive documentation about micro-agents
* Updated sidebar structure for better organization

The changes are well-written, clear, and provide good examples.

**Comment by neubig** [comment]
I have reviewed the changes and they look good:

* Added clear instructions for customizing OpenHands for specific repositories
* Added comprehensive documentation about micro-agents
* Updated sidebar structure for better organization

The documentation is well-written, clear, and provides good examples. The PR can be merged once it is marked as ready for review.

Note: I tried to mark the PR as ready for review through the API but was unable to do so, likely due to API token permissions or because the PR was created by another user. Please mark it as ready for review manually and then it can be merged.

**Comment by neubig** [comment]
I have reviewed the changes and verified that:

1. The documentation in `micro-agents.md` accurately describes the micro-agents system and provides comprehensive guidance on creating custom micro-agents, matching the actual implementation in `openhands/agenthub/codeact_agent/micro/`.

2. The documentation in `prompting-best-practices.md` has been updated with a new section on customizing prompts for specific repositories using `.openhands_instructions` file, matching the implementation in PR #4983.

3. The sidebar structure in `sidebars.ts` has been updated to organize prompting-related documentation better, with a new "Prompting" category containing "Best Practices" and "Micro-Agents" sections.

All changes look good and match the requirements from issue #5527. The PR has been reviewed and approved by @neubig. Please mark the PR as ready for review so it can be merged.

**Pull request merged**
