### PR TITLE
Fix issue #5076: Integration test github action

### LINKED ISSUE #5076: Integration test github action
The eval-runner workflow from the .github/workflows directory is too big. Read it all carefully, and note how it's doing two different things: integration test evaluation and SWE-Bench evaluation. Let's split it:
1) find the section named "Run integration test evaluation" and the necessary sections before and after
2) create a new workflow named integration-runner
3) define it as to work on a PR with the label 'integration-test' trigger
4) move the integration test evaluation section to the new file and copy the prerequisites.

IMPORTANT:
- the action should run only when labeled or manually triggered.

### PR DESCRIPTION
**Pull request by openhands-agent**
This PR proposes re-addition/fixes to integration tests:
- refactor them out of the `eval-this` workflow
- running nightly on Haiku and Deepseek, and on label `integration-test`
- the reason for both Haiku and Deepseek is mainly:
    -  they're cheap LLMs
    - Haiku has native function calling
    - Deepseek doesn't - which allows us to see that/how both types work.
- tested on https://github.com/enyst/playground/issues/9
- fixes to the tests.

Example latest run last night:

image

Please note that Haiku and Deepseek would need to be set up, if we want to do this here. Deepseek has been set up in the past, but it's not working (key depleted?).
Just please let me know which LLMs or how do you think we could we do something like this here. Meanwhile, you can see them chilling just fine in my playground. 😅

---

**Original `openhands-agent` message**

This pull request fixes #5076.

This issue has been successfully resolved. The PR effectively:

1. Separated the large eval-runner workflow into two distinct workflows:
   - A new `integration-runner.yml` for integration tests
   - The original `eval-runner.yml` now focused solely on SWE-Bench evaluation

2. Properly configured the triggers for the new integration-runner workflow to only execute:
   - When a PR is labeled with 'integration-test'
   - When manually triggered via workflow dispatch

3. Successfully moved all necessary prerequisites and configuration sections related to integration testing to the new workflow file while maintaining the functionality.

The solution meets all requirements specified in the original issue, particularly the important condition that the action should only run when labeled or manually triggered. The separation of concerns will make the workflows more maintainable and focused on their specific tasks.

Recommended for review and merge as this represents a clean separation of the evaluation workflows without changing their core functionality.

Automatic fix generated by [OpenHands](https://github.com/All-Hands-AI/OpenHands/) 🙌

---

To run this PR locally, use the following command:
```
docker run -it --rm   -p 3000:3000   -v /var/run/docker.sock:/var/run/docker.sock   --add-host host.docker.internal:host-gateway   -e SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:e5b5bf0-nikolaik   --name openhands-app-e5b5bf0   docker.all-hands.dev/all-hands-ai/openhands:e5b5bf0
```

### CODE REVIEW

**Comment by enyst** [comment]
@openhands-agent The last run-integration-tests job, which was added by this PR, has failed. Use the github API to retrieve and read the job logs, and fix it.

**Comment by enyst** [comment]
image

**Comment by mamoodi** [comment]
I think enyst has eyes on this.

**Review by xingyaoww — APPROVED** [review]
LGTM!

**Comment by mamoodi** [comment]
Also did you get Haiku and Deepseek setup? Referring to the description:
"Please note that Haiku and Deepseek would need to be set up, if we want to do this here. Deepseek has been set up in the past, but it's not working (key depleted?)."

**Comment by enyst** [comment]
> Looks good! Just had a question for my own curiosity. Do you know the cost associated with running these integration tests daily for haiku and deepseek?

They're 6 tasks, each limited to 10 iterations max. 2/6 go on the internet. Nevertheless, the costs I'm seeing with Haiku are USD 0.02-0.05 per task.

Deepseek is lower.

I will fix this to display them all by default. I think it looks super reasonable, though?

**Review by mamoodi — APPROVED** [review]

**Pull request merged**
