### PR TITLE
fix: custom runtime image won't work for go

### PR DESCRIPTION
**Pull request by xingyaoww**
**What is the problem that this fixes or functionality that this introduces? Does it fix any open issues?**

Fix https://github.com/OpenDevin/OpenDevin/issues/3415

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

- Fix test fixture for different runtime images
- Change `su -` to `su` to retain all the env vars and fix the go not found issue

---
**Other references**

### CODE REVIEW

**Review by rbren — APPROVED** [review]

**Comment by tobitege** [comment]
Please note, that "test_runtime.py" is NOT run in CI!

**Comment by xingyaoww** [comment]
@tobitege i think the "Test runtime" testcase were running?

**Comment by xingyaoww** [comment]
@tobitege bc we run them in a separate workflow: https://github.com/All-Hands-AI/OpenHands/blob/a7dfd5b9facc5726369152d10853c99df3c5c88e/.github/workflows/ghcr_runtime.yml#L194

**Comment by xingyaoww** [comment]
@tobitege on a second note, we should probably move `test_runtime` out of that directory and break it down to multiple files to avoid similar confusions in the future :D

**Pull request merged**
