### PR TITLE
fix(frontend): Error when API key is not entered is not clear #4236

### PR DESCRIPTION
**Pull request by Yashwanth-Chandrakumar**
**Give a summary of what the PR does, explaining any non-trivial design decisions**

Added a modal for prompting the user to input an API Key in settings during startup and in session.

**Link of any specific issues this addresses**

#4236

### CODE REVIEW

**Comment by amanape** [comment]
Something isn't right here. You're changing all the files in the repo. Please try creating a new PR or fresh install and only include the changes related to the issue

**Comment by Yashwanth-Chandrakumar** [comment]
I ran linting from my side using poetry run pre-commit run --all-files --config ./dev_config/python/.pre-commit-config.yaml
is that causing the issue.

**Comment by tobitege** [comment]
Make sure you forked the repo NOT from within Windows, but WSL/Linux. I fear that all the linbreaks are wrong in your local copy.

**Comment by Yashwanth-Chandrakumar** [comment]
@tobitege ok let me check

**Pull request closed without merging**
