### PR TITLE
[Fix] Added support to specify the platform on which the runtime image should be built. 

### PR DESCRIPTION
**Pull request by AlexCuadron**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
The pull request introduces a new feature that allows for the platform specification on which runtime images should be built. This enhancement is particularly beneficial for cross-platform development, enabling developers to target specific platforms such as `linux/amd64` or `linux/arm64`. The addition of a platform parameter across various methods and functions ensures that the build process can be tailored to the desired architecture.

Key changes include the integration of the platform parameter into the `RuntimeBuilder` class and its subclasses, such as `DockerRuntimeBuilder` and `RemoteRuntimeBuilder`. This parameter is used to specify the target platform for the build, with a default value of `linux/amd64` to maintain backward compatibility. Additionally, the command-line interface (CLI) is updated to include a `--platform` argument.

The design of this feature is carefully considered to integrate seamlessly with existing code, minimizing disruption while adding new functionality. By setting a default platform, the changes ensure that existing workflows remain unaffected unless a different platform is explicitly specified.

---
**Link of any specific issues this addresses**
Solves issue #4401

### CODE REVIEW

**Comment by AlexCuadron** [comment]
Hey @xiangyue9607  ! Could you please disable the approval requirement for tests to start? Currently, approval is needed every time there’s a merge from the main branch.

**Comment by tobitege** [comment]
> Hey @xiangyue9607 ! Could you please disable the approval requirement for tests to start? Currently, approval is needed every time there’s a merge from the main branch.

This is more a safety measure to not enable them by default.

**Comment by tobitege** [comment]
@rbren I'm not sure a specification of a platform as parameter is desired as OH is built as dual-platform images? 🤔

**Comment by AlexCuadron** [comment]
I initially thought it wasn't necessary, but the issue arises when the FROM image being pulled doesn't match the architecture of the OS performing the build. This mismatch can cause problems, such as those seen in issue #4401.

**Review by xingyaoww — COMMENTED** [review]
Thanks for the fix! 

It will be nice if we can default `platform` to `None` (eg, not passing anything to docker build command) and add it as a configurable value in `SandboxConfig` (default to None):

https://github.com/All-Hands-AI/OpenHands/blob/2cf77e2589060543c2b1ba2841d965d69c2e368b/openhands/core/config/sandbox_config.py#L8-L51

Then we can hardcode the platform to be amd64 on SWE-Bench run_infer script:

https://github.com/All-Hands-AI/OpenHands/blob/2cf77e2589060543c2b1ba2841d965d69c2e368b/evaluation/swe_bench/run_infer.py#L128-L137

This way, we can build amd64 image for only SWE-Bench images, but no the other (OpenHands images are built on Github and support both arm64 and amd64).

**Comment by AlexCuadron** [comment]
Sounds good 👍

**Comment by AlexCuadron** [comment]
Done! Done! PTAL again @xingyaoww

**Review by xingyaoww — APPROVED** [review]
LGTM! Thanks a lot for your contribution!

**Pull request merged**
