### PR TITLE
check node.js req for 20.x or later

### PR DESCRIPTION
**Pull request by ketan1741**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
- Fixes `node.js` version `>=20.x` requirement in `Makefile` and `Development.md`

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Review by enyst — APPROVED** [review]
Thank you! I assume you tested the makefile?

**Comment by ketan1741** [comment]
> Thank you! I assume you tested the makefile?

on it, `if [ "$${NODE_VERSION_ARRAY[0]}" -gt 20 ]` do you want me use `ge` or `gt`?

**Comment by enyst** [comment]
Not my field, but I must have seen we're using 22 in fact... Cc: @amanape

**Comment by ketan1741** [comment]
> Not my field, but I must have seen we're using 22 in fact... Cc: @amanape

yeah I see that[ here](https://github.com/All-Hands-AI/OpenHands/blob/157ff4a4b905e12f973a3ac4d2053a65212fe031/docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage/custom_sandbox_guide.md?plain=1#L13) too

**Comment by ketan1741** [comment]
@enyst Hey, do we merge this?

**Comment by enyst** [comment]
Sure, thanks!

**Pull request merged**
