### PR TITLE
Ketan simplified co act workflow

### PR DESCRIPTION
**Pull request by ketan1741**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**

* This PR implements a simplified multi-agent workflow inspired by the [CoAct paper](https://arxiv.org/abs/2406.13381).
* Currently, in swe-bench eval, there are complex instances that OpenHands fails, especially ones that single CodeActAgent overlooks the buggy location. If we have a grounding test case for the issue, this workflow seems to help.
* An overkill-ish successful trajectory with replanning can be found [here](https://www.all-hands.dev/share?share_id=5d279ec840834fb326c8f3a2fcfc108bcbb27e4793c6a329e6515fa301c448ac).
* A task which CoActPlannerAgent finished but CodeActAgent failed (I expected both to be able to complete it):
[CoAct traj](https://www.all-hands.dev/share?share_id=197cb024a7eee24c8373b3ac1bbc5e905d274bbe0a869c3c4b7705158bcf4de6)
[CodeAct traj](https://www.all-hands.dev/share?share_id=6be13d7296b6bdfefdfc6e6a3a21e21198716a2ecd4494dd4962787f5105abe7)

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
* Modify CodeAct to make it accept delegated task.
* Implement 2 new agents, planner and executor with the same abilities as CodeAct, different system prompts, additional action parsers.

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Comment by neubig** [comment]
Hey @ketan1741 , I'm confused. How does this relate to https://github.com/All-Hands-AI/OpenHands/pull/3770 ?

**Comment by ketan1741** [comment]
> Hey @ketan1741 , I'm confused. How does this relate to #3770 ?

Hey, Prof. @neubig! Hoang wanted me to have a different branch I were to make updates to the workflow to make it more reliable/improve it.

**Comment by neubig** [comment]
Ah, I see. We can figure this out.

**Comment by mamoodi** [comment]
Hi @ketan1741 this PR was marked as stale because it hasn't had any activity in 30 days. Did you want to close it and reopen if it became ready again? Or is it being actively worked on?

**Comment by ketan1741** [comment]
> Hi @ketan1741 this PR was marked as stale because it hasn't had any activity in 30 days. Did you want to close it and reopen if it became ready again? Or is it being actively worked on?

Hey! Thanks for checking in. Yes, sorry I forgot to close this PR. I am working on it on a different branch after the latest refactoring. 
I will open a new one once I feel it is ready.

cc: @srishti-chouhan @bhaavanaa

**Pull request closed without merging**
