### PR TITLE
Devin/1734193391 improve instructions UI

### PR DESCRIPTION
**Pull request by njisaf**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

---
**Link of any specific issues this addresses**

Fixes: https://github.com/All-Hands-AI/OpenHands/issues/5538

### CODE REVIEW

**Comment by neubig** [comment]
This PR is only partially implemented, much of the functionality is left as TODO. I will ask OpenHands to fix it and update the PR.

**Comment by neubig** [comment]
@openhands-agent please reproduce the failing Python Unit Tests GitHub workflow, and iterate on a fix.

**Comment by openhands-agent** [comment]
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the pr! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12332449146).

**Comment by iamEvanYT** [comment]
@neubig 
Screenshot 2024-12-14 at 11 16 28 PM
[Workflow Problem](https://github.com/All-Hands-AI/OpenHands/actions/runs/12332449146/job/34420280654)

**Comment by neubig** [comment]
I have fixed the linting issues in this PR. The following changes were made:

1. Reordered imports in `openhands/server/app.py`
2. Improved formatting in `tests/unit/test_instructions.py`

Please review the changes and let me know if any further modifications are needed.

**Comment by neubig** [comment]
I have pushed the latest changes to the fork. The linting issues should now be resolved. Please review the changes and let me know if any further modifications are needed.

**Comment by neubig** [comment]
I have resolved the merge conflicts and pushed the changes to the `openhands-workspace` branch. Please review the updated changes.

**Comment by neubig** [comment]
This is not working and got a bit messy. We might want to start from scratch with a more detailed plan.

**Pull request closed without merging**
