### PR TITLE
[Resolver] Support custom env vars for Openhands agents

### PR DESCRIPTION
**Pull request by malhotra5**
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

This PR allows users to pass custom env variables to the openhands runtime. This is tough to achieve in Github actions natively as Github doesn't allow for dynamic manipulation of secrets. How this PR works - 

1. User creates a repo secret with the prefix `OPENHANDS_ENV_`
2. ALL secrets are passed to the reusable workflow
3. Secrets are filtered by prefix `OPENHANDS_ENV_` and replaced with `SANDBOX_ENV_` (this allows openhands agents to have access to env vars in its runtime)

### Pros/Cons
This is quite simple for the user to setup. The downside is ALL secrets are passed to the reusable workflow, which isn't ideal in terms of granularity.

### Sample Test
[Issue addressed
](https://github.com/malhotra5/test-repo/issues/16) -  This issue requires openhands to run an api with the custom env variable. Openhands would fail unless the env var exists in its runtime.
[Workflow logs
](https://github.com/malhotra5/test-repo/actions/runs/11943944465/job/33293967361)
#### 1: Filter before sending
1. The caller workflow would require a separate job to filter secrets by prefix (the "`env job`")
2. The caller would encrypt the secrets
3. `env job` would pass the encrypted value (through its output, which makes the encrypted value visible) to the job which invokes the reusable workflow
4. The reusable workflow is invoked with the encrypted secrets
5. Reusable workflow will decrypt the secrets and pass them to `Openhands`

We need an encryption scheme as github actions don't support a native way to pass secrets between jobs (and filtering secrets cannot be performed inside the job calling the reusable workflow).

I'm thinking symmetric key encryption using GNU Privacy Guard would work to achieve this. The user would need to perform just one additional step to setup a `PASSPHRASE` in their repo secrets.

#### 2: Key store
Add support for custom env vars via integrations to external key stores. For example, AWS Secrets Key manager. 

---
**Link of any specific issues this addresses**
#5132

### CODE REVIEW

**Comment by malhotra5** [comment]
> Could you please document this functionality?

Got it will update this PR with documentation.

> Also, what do you mean by "the downside is all secrets are passed to the reusable workflow"? I thought that only ones that start with OPENHANDS_ENV are passed.

The [changes](https://github.com/All-Hands-AI/OpenHands/pull/5156/files#diff-637635829b269b68952b3b210634538198038d21cf6fe5df646fb05c28df87a0#L47
) introduced in  `openhands/resolver/examples/openhands-resolver.yml` passes `toJSON{{ secrets }}` (the stringified representation of ALL repo secrets) for the `ENV_CONFIG` parameter in the reusable workflow. We filter every secret contained inside `ENV_CONFIG` by the prefix `OPENHANDS_ENV` in the reusable workflow.

Ideally, the filtering is performed inside `openhands/resolver/examples/openhands-resolver.yml` **before** it is passed to the reusable workflow (but it's tough to achieve). 


Now that I think about it, this PR doesn't address the fact that the resolver has access to ALL repo secrets at some point (either in the example or reusable workflow). It would make sense to migrate to using environment secrets. This will ensure `openhands/resolver/examples/openhands-resolver.yml` only has access to secrets inside its environment, as opposed to having access to all repo secrets.

**Comment by malhotra5** [comment]
Correction: environment secrets don't help solve the problem of guaranteeing `openhands-resolver` doesn't receive access to any secrets other than the few it needs. 

If the user doesn't want `openhands-resolver` to have access to certain secrets, it becomes their responsibility to store it inside an environment.

Thus, also doesn't matter whether we process `OPENHANDS_ENV` prefix in the caller or called workflow (they're functionally the same; doing it in the called workflow is easier to implement). 

I believe this implementation should suffice; will update with documentation shortly

**Comment by neubig** [comment]
I'm still trying to fully understand this, let's arrange a time to chat quickly to hash it out!

**Comment by oconnorjoseph** [comment]
Hey @neubig @malhotra5 we'd very much appreciate this feature. Could you guys elaborate on why this had to be abandoned?

**Comment by oconnorjoseph** [comment]
Hey @neubig @malhotra5 we'd very much appreciate this feature. Could you guys elaborate on why this had to be abandoned?

**Comment by malhotra5** [comment]
Hi @oconnorjoseph!


## Context
We know users store secrets for both openhands and other purposes in the same repo. For example 

1. OPENHANDS_LLM_API_KEY 
2. SOME_OTHER_KEY


We wanted to implement the ability to provide custom envs and pass them in using a prefix. For example, anything with `OPENHANDS_ENV_{rest}` would be passed to openhands resolver

## Design
How this would work - 
1. There is a workflow that's kept in the users' repo
2. It calls the reusable workflow from the `Openhands` repo


So, we need to first filter all the secrets and pass them inside a single parameter `CUSTOM_SECRETS` to the workflow inside Openhands

## Problem
Github workflows use "jobs". The users' workflow (which calls the `Openhands` workflow), at the moment performs exactly one job - calling the `Openhands` workflow.

We need to be able to filter the users' secrets that match the prefix `OPENHANDS_ENV_`; however, the job which calls another workflow cannot do anything besides calling another workflow. This means, we need to filter the secrets in a separate job. 

So, the current solution is Job 1 filters the secrets, passes the secrets to Job 2. Job 2 calls the reusable workflow and also passes along the secrets.

The problem arises during this "passing" phase. The only way to pass secrets between jobs is through the job "output", which is exposed to the public. Secrets cannot be passed through the output as they will be present in the raw logs. In fact, Github jobs explicitly prevent you from doing this, and will throw an error. 

## Probable solutions
1. In Job 1, filter the keys and encrypt them. Pass them through the job output (and we don't care if they get exposed because its encrypted), and pass it to the reusable workflow. In the reusable workflow, decrypt the secrets and use them. (This is high friction for the user as they need to maintain an encryption key, and complicates things)
2. Pass every secret in the repo to the reusable workflow, and filter them later (we definitely don't want to do this)
3. Possibly use a Github App and Openhands SAAS (we're looking into this)

**Comment by oconnorjoseph** [comment]
> 3. Possibly use a Github App and Openhands SAAS (we're looking into this)

Looks like this is the approach in #5050

**Pull request closed without merging**
