### PR TITLE
[eval] refactor process instance logic into `update_progress` 

### PR DESCRIPTION
**Pull request by xingyaoww**
**Short description of the problem this fixes or functionality that this introduces. This may be used for the CHANGELOG**

The fixes in https://github.com/All-Hands-AI/OpenHands/pull/3854 fix most multi-processing issue, but at some point, we'd get errors like:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-109' coro=<Runtime.on_event() done, defined at /home/xingyaow/OpenDevin-dev/openhands/runtime/runtime.py:111> exception=HTTPError('404 Client Error: Not Found for url: https://21ca5bc7-c846-49b5-a77a-1287ad5d6069.runti
me.all-hands.dev/alive')>
```

Because we never directly called `future.result()` which cause asyncio to complain - this gets evaluation to stuck.

See relevant info [here](https://stackoverflow.com/questions/46890646/asyncio-weirdness-of-task-exception-was-never-retrieved).

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

This PR tries to fix this by:
- (1) refactoring all the exception handling into `update_progress` function, and get rid of the previous `process_instance` wrapper.
- (2) always call `future.results()` inside `update_progress` and handle exception from there

---
**Link of any specific issues this addresses**

### CODE REVIEW

**Comment by xingyaoww** [comment]
Just ran 200+ instances without error - this fix should be effective

**Review by neubig — APPROVED** [review]
LGTM!

**Comment by enyst** [comment]
I still got one. 😢 
The run started on this branch, prior to merge:
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-271' coro=<Runtime.on_event() done, defined at /Users/enyst/repos/odie/openhands/runtime/runtime.py:109> exception=HTTPError('503 Server Error: Service Temporarily Unavailable for url: https://db4e7849-a925-4010-90fb-165ff5e1c6d9.runtime.all-hands.dev/alive')>
Traceback (most recent call last):
  File "/Users/enyst/repos/odie/openhands/runtime/runtime.py", line 115, in on_event
    observation = self.run_action(event)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/enyst/repos/odie/openhands/runtime/remote/runtime.py", line 238, in run_action
    self._wait_until_alive()
  
...

requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://db4e7849-a925-4010-90fb-165ff5e1c6d9.runtime.all-hands.dev/alive
```

Remote runtime, 12 instances queue, num_workers = 4
Cc @xingyaoww

**Comment by xingyaoww** [comment]
@enyst ugh 😣 ... Let's debug on this again.. this is very weird

**Pull request merged**
